### PR TITLE
sonar-scanner with -Dsonar.qualitygate.wait=true support

### PR DESCRIPTION
**Pull request by kumbasar**
`sonar-scanner` is not printing the `ANALYSIS SUCCESSFUL, you can browse` line in the build log if `-Dsonar.qualitygate.wait` flag is set to `true`. Therefore, the plugin skips the SonarQube data part. [By default this flag is false](https://docs.sonarqube.org/latest/analysis/ci-integration-overview/). The plugin works fine if this flag is unset or set to `false`. Also, see https://github.com/jenkinsci/influxdb-plugin/pull/129

**Solution**:
Instead of parsing this above string pattern, we can use below line to parse the SonarQube URL if `-Dsonar.qualitygate.wait=true` :

```bash
QUALITY GATE STATUS: PASSED - View details on https://**************
```

Also, the plugin will skip the `waitForQualityGateTask` method  if `-Dsonar.qualitygate.wait=true`. 

**Tests**
1. If `-Dsonar.qualitygate.wait=true` 
image

2. If `-Dsonar.qualitygate.wait=false`
image

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by kumbasar** [comment]
@asimell are you fine with these changes? Or did I miss something?

**Comment by asimell** [comment]
@kumbasar I haven't had time to review these changes yet. I've had a busy week and I will try to have a look at this still this week.

**Review by asimell — APPROVED** [review]
LGTM

**Comment by kumbasar** [comment]
@asimell can you please give us a hint for the next release target?

**Comment by asimell** [comment]
@kumbasar Probably still this week. "Actual" work has kept me quite busy for a few weeks now. I can maybe squeeze it in today. The release creation doesn't actually really take that long, but I'm getting a bit paranoid with SonarQube generator changes, so I just want to test it well manually as well.

**Pull request merged**
