### PR TITLE
Add the ability to programatically add/remove a target

### PR DESCRIPTION
**Pull request by scoheb**
Added in favour of #44

### CODE REVIEW

**Comment by asimell** [comment]
Development branch is now set up to date with master. @scoheb Can you redirect this PR to development branch instead of master?

**Comment by scoheb** [comment]
@asimell switched to target development

**Comment by scoheb** [comment]
Hi!

Any chance you will be cutting a release soon?

**Comment by asimell** [comment]
@scoheb I just did a release during the week, so I will probably wait a week and see if I can squeeze some more PRs/issues into the next release.

**Comment by scoheb** [comment]
Hi,
Just wondering if you will be cutting a release soon? it has almost been 2 weeks since last one.
Thanks

**Comment by asimell** [comment]
Hi,
I was on my honeymoon until Sunday and had no intention of doing anything related to this plugin until it was over.

I noticed that when I uploaded my current development version that Jenkins lost all existing InfluxDB configurations. Doesn't seem to appear with version 1.18, so if it's because of some change in the development version, I need to change that before I can make a release.

**Comment by scoheb** [comment]
@asimell In that case, Congratulations!

**Pull request merged**
