### PR TITLE
further SonarQube metrics 

### PR DESCRIPTION
**Pull request by I3urny**
This is based on PR #82
I couldn't find a way to add something to @kaankalendr's branch so I figured I'd open a new PR

This PR:
-  fixes the metric key for lines_of_code 
- inserts null for non-existant values (i.e branch_coverage, when no branches exist) 
- adds 2 tests (1 for existing metric and 1 for missing metric)

### CODE REVIEW

**Comment by asimell** [comment]
@I3urny So is this a completely separate PR or would this PR need #82 to be merged first?

**Comment by I3urny** [comment]
It is a seperate PR. It contains the commit from @kaankalendr. 

I assume your CI checks merge the branch with the current development branch, right? I've had a look at it and the error is due to the changes you've made to the constructor and me using the previous format in my tests. 

@Asimell Should I merge the current development branch into this PR and change the tests accordingly so the CI checks work?

**Comment by asimell** [comment]
So merging this will make #82 obsolete?

There were some compilation failures (https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Finfluxdb-plugin/detail/PR-94/2/pipeline), more precisely

`[2020-03-09T02:43:29.629Z] [ERROR] /mnt/agent-workspace/workspace/Plugins_influxdb-plugin_PR-94/src/test/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGeneratorTest.java:[68,79] incompatible types: jenkinsci.plugins.influxdb.renderer.MeasurementRenderer<hudson.model.Run<?,?>> cannot be converted to hudson.model.Run<?,?>`
`[2020-03-09T02:43:29.629Z] [ERROR] /mnt/agent-workspace/workspace/Plugins_influxdb-plugin_PR-94/src/test/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGeneratorTest.java:[80,79] incompatible types: jenkinsci.plugins.influxdb.renderer.MeasurementRenderer<hudson.model.Run<?,?>> cannot be converted to hudson.model.Run<?,?>`

Could you try to fix those before I proceed?

**Comment by asimell** [comment]
@I3urny Sorry, I just noticed your edited message. Yes, please do the changes. :)

**Comment by I3urny** [comment]
@asimell Yes, this PR will make #82 obsolete.

**Comment by asimell** [comment]
@I3urny Could you also update the `README.md` documentation on the updated `sonarqube_data` metrics?

**Comment by I3urny** [comment]
@asimell Done. Anything else?

**Comment by asimell** [comment]
@I3urny Cheers, the PR looks good otherwise. Just running some tests against it before merging.

**Pull request merged**
