### PR TITLE
Add support for Serenity metrics

### PR DESCRIPTION
**Pull request by trashytop**
**Summary of this PR**
Collects data from a Serenity report and sends the metrics to an InfluxDB instance.

**How should this be manually tested?**
Run Serenity in a Jenkins job (using either Maven or Gradle) with the JSON summary report enabled.  The InfluxDB plugin for Jenkins will then extract the data from the report and send the metrics to the configured InfluxDB instance.

**Side effects**
None,

**Documentation**
README.md has been updated.

**Relevant tickets**
JENKINS-60687

### CODE REVIEW

**Comment by asimell** [comment]
Hi, thanks for the PR! In general the PR looks good. However, you've parsed the Serenity reports yourself instead of getting data from the Serenity plugin, so checking this requires a bit more testing.

Typically, I want InfluxDB plugin to just collect data from other plugins. If the data is incorrect, it's because the other plugin is parsing it wrong, so it's less maintenance work for me in the future.

**Comment by trashytop** [comment]
Thanks Alex.

The InfluxDB plugin is no longer used/supported/needed – all reports are generated via Maven/Gradle.

I recently extended Serenity to generate a machine-readable JSON summary report (see https://github.com/serenity-bdd/serenity-core/pull/1929 and https://github.com/serenity-bdd/serenity-core/pull/1943) to make the parsing easier.

Hope this is ok.

**Comment by asimell** [comment]
I guess you mean Serenity plugin? :)

And yes, this is fine, but as I said, I need to verify it properly that this behaves as intended.

**Comment by trashytop** [comment]
Thanks Aleksi.   Yes - https://github.com/jenkinsci/serenity-plugin.

BTW, to test you will either need to build serenity-core yourself or wait a few days for a new release, as https://github.com/serenity-bdd/serenity-core/pull/1943 has been merged to master but not released yet.

Hopefully the JUnit tests I've included help raise confidence - the test JSON summary file is a real one, generated yesterday.

**Comment by trashytop** [comment]
@asimell -  serenity-core release 2.1.5+ (see https://github.com/serenity-bdd/serenity-core/releases/tag/v2.1.5) generates the json summary report.  Can you please verify that this PR behaves as intended, i.e. extracts the metrics from this report and sends them to InfluxDB? Many thanks.

**Review by asimell — APPROVED** [review]

**Pull request merged**
