### PR TITLE
JENKINS-65115 Fix JUnit test name to be full name

### PR DESCRIPTION
**Pull request by nigelarmstrong-bc**
JUnit test names are missing the package and class names. Since this may be breaking, I put it to be included in the 3.0 release. 

Junit names include the stage closure and the test function name, but not the test package or class. This can be confusing when multiple tests exist with the same function name, but different classes or package paths. 

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by asimell** [comment]
Hi @nigelarmstrong-bc ! Thanks for your contribution!

Could the package name be just added as an extra field instead of replacing existing one? Something like `test_full_package_name`, so it would not break existing usage, but would allow usage of full package names in the future.

Also, please update [available metrics](https://github.com/jenkinsci/influxdb-plugin/blob/development/doc/available_metrics.md) documentation when changing metrics.

**Comment by nigelarmstrong-bc** [comment]
Sure. I can do that. I originally did that, but then decided to do it this way since the current implementation feels incorrect given that it doesn't actually give the full name of test test in the `test_name` field/tag. 
I can add this as a new field and tag, but overall I think the overall structure of the junit data is confusing, because the test name includes the closure path for the pipeline step and the name of the test function, then a separate field will contain the package and class name. 

For example: 
(current)
`test_name`: `Tests / Test Stage 1 / my_test_function`

(my current proposal)
`test_name`: `Tests / Test Stage 1 / mypackage.subpackage.MyClass.my_test_function`

(your recommendation)
`test_name`: `Tests / Test Stage 1 / my_test_function`
`test_full_class_name`: `mypackage.subpackage.MyClass`

(what I think is more intuitive)
`test_name`: `my_test_function`
`test_full_class_name`: `mypackage.subpackage.MyClass`
`pipeline_step`: `Tests / Test Stage 1`

Note: `Tests` and `Test Stage 1` are stage names in a jenkinsfile.

**Comment by asimell** [comment]
Yes, I think the last option is by far the most intuitive (which is what I thought the implementation was currently, without the class name and pipeline_step of course).

Note that in my project I don't personally use `junit_data` (or a few others) for anything, so I have gracefully put those somewhere to the back of my head. So, for some measurements I can't immediately say what they do without having a separate look at source code.

**Comment by nigelarmstrong-bc** [comment]
Do you think that a move to the more intuitive option is worth it, even though it is a breaking change? 

To me it seems worth it. Of course there will be some issue during the change, but in my use we mostly look at very recent `junit_data` and a transition will only cause us a little trouble for a week or so. Obviously, I don't know how this will affect other users though.

**Comment by asimell** [comment]
Yes, I think it's worth it. The next release will be 3.0, so there's some breaking changes coming anyway. As long as all the breaking changes are well documented, users shouldn't have _too_ much trouble fixing their configurations.

**Comment by nigelarmstrong-bc** [comment]
I have pushed the split fields/tags. There is an issue with the dependencies. I know that the dependency for `org.jenkins-ci.plugins.junit` must be at least `1.23` but I cannot figure out how to correctly update the pom to fix the other dependency issues.

**Comment by asimell** [comment]
@nigelarmstrong-bc I'm working on that on another feature. I'll merge that (probably) in an hour or so. You can merge `development` to your branch and it should hopefully resolve that issue.

**Comment by asimell** [comment]
LGTM

**Pull request merged**
