### PR TITLE
Allow to use Jenkins global proxy when connecting to Influx server

### PR DESCRIPTION
**Pull request by Mariushrek**
Now, during setting new connectivity to InfluxDB it is able to use proxy from Jenkins.

### CODE REVIEW

**Comment by Mariushrek** [comment]
Aloha,

Any comments?

**Comment by asimell** [comment]
Hi @Mariushrek and sorry for a longer response time. While I was looking at this PR I found out https://issues.jenkins-ci.org/browse/JENKINS-48382 and have been trying to fix that before merging this. That issue has been quite a tough one and I would _really_ like to get it fixed before adding more checkboxes for the global configuration. I believe it has something to do with the dependencies, but changing those dragged me into a swamp of outdated dependencies. Try to bear with me :)

**Comment by Mariushrek** [comment]
@asimell Understand now :) 
Thanks for your response, I will wait for you and news :)

**Comment by asimell** [comment]
An update to this. I found out that the issue I posted has already existed in 2012, so it's not InfluxDB plugin related, so I can finally review this PR.

**Comment by Mariushrek** [comment]
Sorry for late response - sounds great :)

**Pull request merged**
