### PR TITLE
add @Symbol annotation

### PR DESCRIPTION
**Pull request by CCFenner**
**changes:**
- add `@Symbol` annotation to ease use

This makes it possible to call `influxDb(..)` in a pipeline instead of `step([$class: 'InfluxDbPublisher', ..])`

see https://jenkins.io/doc/developer/plugin-development/pipeline-integration/#defining-symbols

### CODE REVIEW

**Comment by CCFenner** [comment]
Unfortunately, I don't know how to unit test this. Any idea?

**Comment by asimell** [comment]
@CCFenner Not sure with unit testing. If some other plugin has unit tests for this, maybe it's worth checking those. Instructions on how to manually test is also better than nothing.

**Comment by darxriggs** [comment]
You could use https://github.com/jenkinsci/jenkins-test-harness with `@JenkinsRule` to really create a pipeline job which uses this symbol. Some good examples can be found at https://jenkins.io/doc/developer/testing/. The question is if it's worth it.

**Comment by asimell** [comment]
Tested this manually with several different configurations and is working just fine. If you manage to write unit tests for this, you can open a new PR.

**Pull request merged**
