### PR TITLE
[JENKINS-64999] - Add support for InfluxDB 2.0

### PR DESCRIPTION
**Pull request by asimell**
InfluxDB 2.0 has been released. This PR adds support for InfluxDB 2.x API.

- Also replaces all deprecated method calls from unit tests to supported ones.

**Breaking changes**

- Changed `influxdb-java` dependency to `influxdb-client-java`, which doesn't support InfluxDB 1.7 or lower. New plugin release supports only InfluxDB 1.8+.

### CODE REVIEW

**Comment by Pauss** [comment]
Hi. I have a question. 
It is possible to configure InfluxDB Plugin credentials within Jenikins UI? I see that start with InfluxDB 2.x api, write operations need 'user token' instead of basic auth. I can't figure out how can I configure this token on InfluxDB plugin within Jenkins UI. Ty.

**Comment by asimell** [comment]
Token authentication is not yet supported. I'm working on it. You can use username+password to authenticate. I just merged a fix for that this week and I'm making a release next week. Sorry for the inconvenience.

**Comment by Pauss** [comment]
Hello, thanks for response :D. 
Hmm I don't understand how can I use 'username+password' since basic auth it's not suported on v2.x on influxDB. 
Maybe I am missing something. 

In the image attached you can see my docker-compose.yaml and a simple request to my inlfuxDB instance. 
image

**Comment by asimell** [comment]
The user needs to have write-access and it should work just fine. However, https://github.com/jenkinsci/influxdb-plugin/pull/126 adds support for authentication token authorization. I'll merge it today and hopefully make the new release today as well.

**Comment by Pauss** [comment]
It has access, the problem is that /api/v2 request for token in order to get access to resources. This is the log I get from influxDB instance: 
 'ts=2022-01-31T08:24:09.089836Z lvl=info msg=Unauthorized log_id=0ZNo3NzW000 error="token required" '

Anyway I will get the update once it's released. Many thanks!

**Pull request merged**
