### PR TITLE
casc compatibility

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by asimell** [comment]
@ndeloof This looks really neat! However, it seems like when I install this version, I'm unable to add any new targets to Jenkins and the old targets cannot be modified or removed in the Jenkins configuration page. Configuration in pipeline jobs work.

**Comment by asimell** [comment]
@ndeloof I made some fixes to my copy of this PR. However, I also get a java.io.NotSerializableException: hudson.util.PersistedList from this PR. This blocks creating new targets in a pipeline.

Does this PR actually implement any other functionality than remove a call for a deprecated function? Does that really need the use a PersistedList?

**Comment by ndeloof** [comment]
I hardly understand why pipeline would require a Descriptor to be Serializable. A descriptor is expected to be a singleton object hosted on master, so should _not_ be serialized in any way. I assume this is a side effect of declaring a static reference on https://github.com/jenkinsci/influxdb-plugin/blob/595fa7bc56/src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublisher.java#L43
which is a deprecated approach, should have Descriptor class annotated with `@Extension` and Notifier not to override the standard `getDescriptor` implementation.
Maybe an opportunity to fix this.

**Comment by asimell** [comment]
The Descriptor itself is not serialized, but the targets list are. Currently, the the targets list in the descriptor is a `List<Target>` and a `CopyOnWriteArrayList<Target>`, which are serializable. Changing the targets list to be a `PersistedList<Target>` makes the list non-serializable once again, thus blocking creating new targets in pipelines.

**Comment by ndeloof** [comment]
Descriptor is declared as Serializable, so my confusion. Why are targets serialized by pipeline ? I only can see a reference to `selectedTarget` in InfluxDbPublisher, I can't find any reason the full list would need to be serialized. Sounds to me like a reference leak which make pipeline logic serialize unnecessary stuff, so my assumption on `DESCRIPTOR` static field. You could run a quick test by removing this field, getDescriptor override, and annotate descriptor as `@Extension`.

**Comment by asimell** [comment]
`selectedTarget` is only a string containing the target's description, while the Descriptor actually contains the list of targets. I still need to get the selected target from the Descriptor in the pipeline.

**Pull request closed without merging**
